### ISSUE TITLE
"unsafe credentials comparison" is not a security bug

### ISSUE THREAD

**Issue by glyph** [ludios/unfixed-security-bugs#3]
The major reason that http://twistedmatrix.com/trac/ticket/4536 remains unfixed is that _no one can demonstrate that it is a bug_, not just that it's not clear if one specific fix helps.  So I object to characterizing it as a security bug.

When I say that nobody can demonstrate that it is a bug, what I mean is not that nobody can demonstrate a working, weaponized attack, but rather that there is any observable difference between the different implementations _whatsoever_.

My hypothesis is that whatever optimizations that Python or libc has applied to vectorizing the string comparison of small values (such as passwords) is already an effective defense against timing attacks since no timing differential can be demonstrated.  If anyone could develop any observable test at all to falsify that hypothesis, i.e. if there were any demonstration that a bug *might* exist, we would apply a fix immediately.

**Comment by ivan** [comment]
Some GitHub searching (to check if anyone has pulled off _any_ kind of timing attack on passwords) revealed that Adrian Hayes @aj-code succeeded with a timing attack on Twisted Web in 2012: http://security-assessment.com/files/documents/presentations/TimingAttackPresentation2012.pdf (slide 34) via https://github.com/aj-code/TimingIntrusionTool5000

I'm not sure if that involved full password recovery, but even narrowing which passwords to guess seems like a security bug.

**Comment by exarkun** [comment]
It looks like it involved full password recovery using the timing attack to narrow down a list password list to make brute-force feasible to finish the job.  This does seem like a security bug.  I'm attempting to reproduce the work described there.

**Comment by glyph** [comment]
@ivan Thanks for digging that up. I guess *this* issue should be closed then, as this is now a known security issue.
