### ISSUE TITLE
Enabled TTY tickets is better than disabled TTY tickets

### ISSUE THREAD

**Issue by boite** [ludios/unfixed-security-bugs#4]
The following could be understood as to imply that disabling TTY tickets is better than having the option enabled:-

> "sudo TTY tickets (generally enabled by default) allow *any subprocess* to do a passwordless sudo within the timeout period, not just commands you've typed into the shell."

However, disabling TTY tickets is less secure than having the option enabled:-

- `Defaults tty_tickets` (enabled): **Any process** can do a passwordless sudo within the timeout period.
- `Defaults !tty_tickets` (disabled): Any subprocess of the TTY can do a passwordless sudo within the timeout period.

**Comment by ivan** [comment]
Good catch, thanks.  I should have complained about credential caching, not tty tickets.
